<?php

/**
 * Keluhan harian per penyakit — label gejala (model chatbot).
 * Skor: tidak ada=0, ringan=1, sedang=2, berat=3.
 */
return [
    'tb_paru' => [
        'batuk' => 'Batuk',
        'dahak' => 'Dahak',
        'sesak_napas' => 'Sesak napas',
        'nyeri_dada' => 'Nyeri dada',
        'demam' => 'Demam',
        'keringat_malam' => 'Keringat malam',
        'nafsu_makan' => 'Nafsu makan menurun',
        'berat_badan' => 'Berat badan menurun',
        'mudah_lelah' => 'Mudah lelah',
    ],
    'dhf' => [
        'demam' => 'Demam',
        'sakit_kepala' => 'Sakit kepala',
        'nyeri_otot' => 'Nyeri otot/sendi',
        'mual_muntah' => 'Mual muntah',
        'nyeri_perut' => 'Nyeri perut',
        'nafsu_makan' => 'Nafsu makan menurun',
        'bintik_merah' => 'Bintik merah/perdarahan',
        'lemas' => 'Lemas',
    ],
    'ppok' => [
        'sesak_napas' => 'Sesak napas',
        'batuk' => 'Batuk',
        'dahak' => 'Dahak',
        'mengi' => 'Mengi (ngik-ngik)',
        'mudah_lelah' => 'Mudah lelah',
        'gangguan_aktivitas' => 'Gangguan aktivitas',
        'gangguan_tidur' => 'Gangguan tidur akibat sesak',
    ],
    'penyakit_ginjal' => [
        'bengkak_kaki' => 'Bengkak kaki',
        'bengkak_wajah' => 'Bengkak wajah',
        'sesak_napas' => 'Sesak napas',
        'mual_muntah' => 'Mual muntah',
        'nafsu_makan' => 'Nafsu makan menurun',
        'kelelahan' => 'Kelelahan',
        'gatal' => 'Gatal-gatal',
        'gangguan_tidur' => 'Gangguan tidur',
        'urin_berbusa' => 'Urin berbusa',
    ],
    'stroke' => [
        'kelemahan' => 'Kelemahan anggota gerak',
        'kesulitan_berjalan' => 'Kesulitan berjalan',
        'gangguan_bicara' => 'Gangguan bicara',
        'gangguan_menelan' => 'Gangguan menelan',
        'pusing' => 'Pusing',
        'gangguan_keseimbangan' => 'Gangguan keseimbangan',
        'kesulitan_aktivitas' => 'Kesulitan aktivitas sehari-hari',
        'nyeri_bahu' => 'Nyeri bahu/lengan',
    ],
    'jantung_koroner' => [
        'nyeri_dada' => 'Nyeri dada',
        'sesak_napas' => 'Sesak napas',
        'jantung_berdebar' => 'Jantung berdebar',
        'mudah_lelah' => 'Mudah lelah',
        'pusing' => 'Pusing',
        'keringat_dingin' => 'Keringat dingin',
        'gangguan_aktivitas' => 'Gangguan aktivitas',
    ],
    'diabetes_melitus' => [
        'sering_haus' => 'Sering haus',
        'sering_bak' => 'Sering buang air kecil',
        'mudah_lapar' => 'Mudah lapar',
        'kelelahan' => 'Kelelahan',
        'bb_turun' => 'Berat badan menurun',
        'luka_sembuh' => 'Luka sulit sembuh',
        'kesemutan' => 'Kesemutan',
        'penglihatan_kabur' => 'Penglihatan kabur',
    ],
    'hipertensi' => [
        'sakit_kepala' => 'Sakit kepala',
        'pusing' => 'Pusing',
        'tengkuk_berat' => 'Tengkuk terasa berat',
        'jantung_berdebar' => 'Jantung berdebar',
        'mudah_lelah' => 'Mudah lelah',
        'gangguan_tidur' => 'Gangguan tidur',
        'penglihatan_kabur' => 'Penglihatan kabur',
    ],
    'rheumatoid_arthritis' => [
        'nyeri_sendi' => 'Nyeri sendi',
        'bengkak_sendi' => 'Pembengkakan sendi',
        'kekakuan_pagi' => 'Kekakuan pagi hari',
        'kemerahan' => 'Kemerahan sendi',
        'kelelahan' => 'Kelelahan',
        'kesulitan_genggam' => 'Kesulitan menggenggam',
        'kesulitan_berjalan' => 'Kesulitan berjalan',
        'gangguan_aktivitas' => 'Gangguan aktivitas sehari-hari',
    ],
];
