<?php

return [
    'tb_paru' => [
        'Rendah' => [
            'items' => [
                'Mengonsumsi makanan tinggi protein',
                'Istirahat 7–8 jam',
                'Melakukan aktivitas fisik ringan',
                'Menggunakan masker di lingkungan berisiko',
                'Menerapkan etika batuk',
                'Rumah memiliki ventilasi baik',
                'Mendapat paparan sinar matahari',
                'Melakukan pemantauan gejala TB',
            ],
        ],
        'Sedang' => [
            'items' => [
                'Menggunakan masker saat batuk',
                'Menutup mulut saat batuk/bersin',
                'Tidak berbagi alat makan',
                'Mengonsumsi makanan tinggi protein',
                'Minum air cukup (≥8 gelas)',
                'Mencatat durasi batuk',
                'Mencatat berat badan',
                'Mencatat demam/keringat malam',
                'Edukasi keluarga mengenai TB',
                'Telah melakukan pemeriksaan kesehatan sesuai anjuran',
            ],
        ],
        'Tinggi' => [
            'items' => [
                'Minum OAT sesuai jadwal',
                'Tidak pernah lupa minum obat',
                'Menggunakan masker setiap hari',
                'Menerapkan etika batuk',
                'Menjaga ventilasi rumah terbuka',
                'Tidur terpisah sementara',
                'Mengonsumsi makanan tinggi protein',
                'Mengonsumsi makanan cukup kalori',
                'Mencatat kepatuhan minum obat',
                'Mencatat berat badan',
                'Mencatat gejala harian',
                'Keluarga membantu pengobatan',
                'Keluarga telah menjalani skrining TB',
            ],
        ],
    ],

    'dhf' => [
        'Rendah' => [
            'items' => [
                'Istirahat cukup (≥8 jam)',
                'Minum cairan minimal 2 liter/hari',
                'Melakukan kompres hangat saat demam',
                'Menggunakan obat sesuai anjuran tenaga kesehatan',
                'Tidak menggunakan aspirin/ibuprofen',
                'Menggunakan lotion anti nyamuk',
                'Menggunakan kelambu/pelindung nyamuk',
                'Memakai pakaian tertutup',
                'Memantau suhu tubuh',
                'Memantau munculnya gejala baru',
                'Melakukan 3M di lingkungan rumah',
                'Membersihkan tempat berkembang biak nyamuk',
            ],
        ],
        'Sedang' => [
            'items' => [
                'Sudah melakukan pemeriksaan ke fasilitas kesehatan',
                'Melakukan pemeriksaan darah sesuai anjuran',
                'Minum cairan 2–3 liter/hari',
                'Mengonsumsi oralit bila dianjurkan',
                'Memantau suhu tubuh',
                'Mencatat frekuensi muntah',
                'Memantau nafsu makan',
                'Memantau jumlah urin',
                'Mengenali tanda fase kritis (hari 3–7)',
                'Menggunakan kelambu/anti nyamuk',
                'Menghindari gigitan nyamuk',
            ],
        ],
        'Tinggi' => [
            'items' => [
                'Bed rest sesuai anjuran',
                'Posisi tubuh nyaman',
                'Minum cairan sesuai toleransi',
                'Tidak memaksakan minum saat muntah berat',
                'Tidak mengonsumsi aspirin',
                'Tidak mengonsumsi ibuprofen',
                'Tidak mengonsumsi obat antiinflamasi lain tanpa anjuran dokter',
                'Keluarga memantau tangan dan kaki dingin',
                'Keluarga memantau denyut nadi cepat',
                'Keluarga memantau penurunan tekanan darah',
                'Keluarga segera membawa ke RS jika muncul tanda syok',
            ],
        ],
    ],

    'ppok' => [
        'Rendah' => [
            'items' => [
                'Tidak merokok hari ini',
                'Menghindari asap rokok',
                'Menggunakan masker saat terpapar debu/polusi',
                'Menghindari asap dapur/biomassa',
                'Jalan kaki/aktivitas fisik ≥20 menit',
                'Melakukan latihan pernapasan',
                'Mengonsumsi makanan tinggi protein',
                'Mengonsumsi buah/sayur (antioksidan)',
                'Minum air cukup',
                'Memantau batuk, dahak, atau sesak',
            ],
        ],
        'Sedang' => [
            'items' => [
                'Kontrol ke fasilitas kesehatan sesuai jadwal',
                'Evaluasi fungsi paru sesuai anjuran',
                'Melakukan Pursed-Lip Breathing',
                'Melakukan Diaphragmatic Breathing',
                'Jalan kaki/latihan fisik rutin',
                'Menghindari aktivitas terlalu berat',
                'Mengikuti rehabilitasi paru (bila tersedia)',
                'Minum cairan cukup',
                'Melakukan teknik batuk efektif',
                'Menghindari asap rokok',
                'Menghindari debu/polusi',
                'Menghindari udara dingin ekstrem',
                'Status vaksin influenza sesuai anjuran',
                'Status vaksin pneumonia sesuai anjuran',
            ],
        ],
        'Tinggi' => [
            'items' => [
                'Menggunakan inhaler sesuai jadwal',
                'Tidak melewatkan dosis obat',
                'Kontrol dokter sesuai jadwal',
                'Latihan napas intensif',
                'Latihan fisik terstruktur',
                'Menerapkan teknik konservasi energi',
                'Istirahat cukup',
                'Mengatur aktivitas agar tidak kelelahan',
                'Konsumsi makanan tinggi protein',
                'Konsumsi kalori cukup',
                'Memantau berat badan',
                'Menggunakan masker',
                'Cuci tangan secara rutin',
                'Menghindari kerumunan saat sakit',
                'Keluarga membantu terapi/perawatan',
                'Keluarga memahami edukasi PPOK',
                'Mencatat sesak napas harian',
                'Mencatat jumlah dahak',
                'Mencatat frekuensi batuk',
            ],
        ],
    ],

    'penyakit_ginjal' => [
        'Rendah' => [
            'items' => [
                'Minum cairan sesuai kebutuhan (1,5–2 liter/hari)',
                'Tidak mengalami dehidrasi',
                'Mengurangi konsumsi garam',
                'Membatasi makanan tinggi lemak',
                'Membatasi makanan/minuman tinggi gula',
                'Mengonsumsi sayur dan buah',
                'Melakukan aktivitas fisik ≥30 menit',
                'Tidak menggunakan NSAID tanpa anjuran dokter',
                'Memantau tekanan darah',
                'Memantau gula darah (jika diperlukan)',
                'Memantau gejala gangguan ginjal',
            ],
        ],
        'Sedang' => [
            'items' => [
                'Tekanan darah terkontrol',
                'Gula darah terkontrol',
                'Mengurangi garam ≤5 gram/hari',
                'Membatasi konsumsi protein berlebihan',
                'Menghindari makanan tinggi natrium',
                'Minum cairan sesuai anjuran',
                'Tidak minum cairan berlebihan',
                'Pemeriksaan tekanan darah sesuai jadwal',
                'Pemeriksaan laboratorium sesuai jadwal',
                'Tidak merokok',
                'Tidak mengonsumsi alkohol',
                'Melakukan manajemen stres',
            ],
        ],
        'Tinggi' => [
            'items' => [
                'Minum obat sesuai resep',
                'Tidak melewatkan jadwal obat',
                'Tidak menggunakan obat tanpa konsultasi',
                'Kontrol dokter sesuai jadwal',
                'Membatasi protein sesuai anjuran',
                'Membatasi garam',
                'Membatasi kalium (bila dianjurkan)',
                'Membatasi fosfor',
                'Mengatur cairan sesuai anjuran dokter',
                'Membatasi cairan saat ada pembengkakan',
                'Menimbang berat badan harian',
                'Memantau pembengkakan kaki/wajah',
                'Memantau jumlah urin',
                'Mencatat hasil monitoring harian',
                'Keluarga membantu mengontrol diet',
                'Keluarga membantu kepatuhan obat',
                'Keluarga memahami edukasi penyakit ginjal',
                'Mengikuti edukasi dialisis bila dianjurkan',
                'Konsultasi dengan spesialis ginjal sesuai jadwal',
            ],
        ],
    ],

    'stroke' => [
        'Rendah' => [
            'items' => [
                'Mengonsumsi makanan rendah garam',
                'Mengurangi lemak jenuh/gorengan',
                'Mengonsumsi buah dan sayur',
                'Membatasi gula',
                'Menghindari makanan olahan',
                'Melakukan aktivitas fisik ≥30 menit',
                'Tidak merokok',
                'Tidak mengonsumsi alkohol',
                'Melakukan pengelolaan stres',
                'Memantau tekanan darah',
                'Melakukan skrining/kontrol kesehatan sesuai jadwal',
            ],
        ],
        'Sedang' => [
            'items' => [
                'Tekanan darah dalam target',
                'Gula darah dalam target',
                'Kolesterol terkontrol',
                'Mengikuti diet DASH/Mediterania',
                'Membatasi garam <5 gram/hari',
                'Mengurangi lemak jenuh/gorengan',
                'Aktivitas fisik 30 menit/hari',
                'Minum obat sesuai resep',
                'Tidak melewatkan jadwal obat',
                'Memantau tekanan darah',
                'Memantau gula darah',
                'Memantau kolesterol sesuai jadwal',
            ],
        ],
        'Tinggi' => [
            'items' => [
                'Minum obat antihipertensi sesuai jadwal',
                'Minum obat antiplatelet/pengencer darah sesuai jadwal',
                'Minum obat diabetes atau kolesterol sesuai jadwal',
                'Tidak menghentikan obat tanpa konsultasi',
                'Kontrol dokter sesuai jadwal',
                'Melakukan latihan fisik sesuai kemampuan',
                'Melakukan latihan bicara (jika diperlukan)',
                'Melakukan latihan keseimbangan',
                'Istirahat cukup',
                'Menghindari aktivitas berlebihan',
                'Diet rendah garam',
                'Mengonsumsi makanan tinggi serat',
                'Membatasi lemak jenuh',
                'Keluarga mendampingi aktivitas harian',
                'Keluarga membantu pengawasan obat',
                'Keluarga memahami tanda bahaya stroke',
                'Memantau tekanan darah',
                'Memantau gejala baru (kelemahan anggota gerak, bicara pelo, wajah mencong)',
            ],
        ],
    ],

    'jantung_koroner' => [
        'Rendah' => [
            'items' => [
                'Mengurangi lemak jenuh dan gorengan',
                'Membatasi garam (<5 gram/hari)',
                'Mengonsumsi buah dan sayur',
                'Mengonsumsi makanan tinggi serat',
                'Melakukan aktivitas fisik ≥30 menit',
                'Tidak merokok',
                'Tidak mengonsumsi alkohol',
                'Melakukan manajemen stres',
                'Memantau tekanan darah',
                'Memantau gula darah (jika diperlukan)',
                'Memantau kolesterol sesuai jadwal',
            ],
        ],
        'Sedang' => [
            'items' => [
                'Tekanan darah dalam target',
                'Gula darah dalam target',
                'Kolesterol dalam target',
                'Mengikuti diet DASH/Mediterania',
                'Membatasi lemak jenuh dan lemak trans',
                'Membatasi gula',
                'Membatasi garam',
                'Aktivitas fisik 30 menit/hari',
                'Minum obat sesuai resep',
                'Tidak melewatkan dosis obat',
                'Memantau tekanan darah',
                'Memantau gula darah',
                'Memantau kolesterol sesuai jadwal',
            ],
        ],
        'Tinggi' => [
            'items' => [
                'Minum obat antihipertensi sesuai jadwal',
                'Minum statin sesuai jadwal',
                'Minum antiplatelet sesuai jadwal',
                'Tidak menghentikan obat tanpa konsultasi',
                'Kontrol dokter sesuai jadwal',
                'Melakukan aktivitas ringan terkontrol',
                'Menghindari aktivitas berat mendadak',
                'Istirahat cukup',
                'Beristirahat saat muncul nyeri dada',
                'Menggunakan obat sesuai anjuran saat gejala muncul',
                'Memantau frekuensi nyeri dada',
                'Diet rendah garam',
                'Diet rendah lemak jenuh',
                'Mengonsumsi makanan tinggi serat',
                'Keluarga membantu pengawasan obat',
                'Keluarga memahami tanda bahaya serangan jantung',
                'Keluarga membantu aktivitas bila diperlukan',
                'Memantau tekanan darah',
                'Memantau keluhan sesak atau nyeri dada',
                'Melakukan pemeriksaan jantung/laboratorium sesuai jadwal',
            ],
        ],
    ],

    'diabetes_melitus' => [
        'Rendah' => [
            'items' => [
                'Menghindari minuman manis',
                'Membatasi makanan tinggi gula',
                'Mengonsumsi sayur dan buah',
                'Mengonsumsi makanan tinggi serat',
                'Memilih karbohidrat kompleks',
                'Aktivitas fisik ≥30 menit',
                'Menjaga berat badan ideal',
                'Tidak merokok',
                'Mengelola stres',
                'Memantau gula darah sesuai jadwal',
            ],
        ],
        'Sedang' => [
            'items' => [
                'Mengurangi karbohidrat sederhana',
                'Mengatur porsi makan sesuai anjuran',
                'Tidak mengonsumsi minuman manis',
                'Aktivitas fisik ≥30 menit',
                'Melakukan latihan aerobik',
                'Melakukan latihan kekuatan',
                'Menjalankan program penurunan berat badan',
                'Memantau gula darah puasa',
                'Pemeriksaan HbA1c sesuai jadwal',
                'Memantau tekanan darah',
                'Mengenali tanda dan gejala diabetes',
                'Konsultasi tenaga kesehatan sesuai jadwal',
            ],
        ],
        'Tinggi' => [
            'items' => [
                'Minum obat antidiabetes sesuai jadwal',
                'Menggunakan insulin sesuai resep (jika ada)',
                'Tidak menghentikan obat tanpa konsultasi',
                'Kontrol dokter sesuai jadwal',
                'Diet rendah gula',
                'Mengontrol jumlah karbohidrat',
                'Mengonsumsi makanan tinggi serat',
                'Menghindari makanan indeks glikemik tinggi',
                'Olahraga rutin sesuai kemampuan',
                'Menghindari duduk terlalu lama (sedentary lifestyle)',
                'Mengukur gula darah mandiri',
                'Mencatat hasil gula darah',
                'Memantau gejala hipoglikemia/hiperglikemia',
                'Memeriksa kondisi kaki setiap hari',
                'Menghindari luka pada kaki',
                'Menggunakan alas kaki yang aman',
                'Keluarga membantu pengawasan diet',
                'Keluarga membantu kepatuhan obat',
                'Keluarga memahami tanda bahaya diabetes',
            ],
        ],
    ],

    'hipertensi' => [
        'Rendah' => [
            'items' => [
                'Membatasi konsumsi garam (<5 gram/hari)',
                'Mengonsumsi buah dan sayur',
                'Mengurangi makanan olahan/instan',
                'Melakukan aktivitas fisik ≥30 menit',
                'Menjaga berat badan ideal',
                'Tidak merokok',
                'Tidak mengonsumsi alkohol',
                'Melakukan manajemen stres',
                'Memantau tekanan darah sesuai jadwal',
                'Mengikuti edukasi kesehatan hipertensi',
            ],
        ],
        'Sedang' => [
            'items' => [
                'Menjalankan diet DASH',
                'Membatasi garam <5 gram/hari',
                'Mengonsumsi makanan tinggi kalium (buah & sayur)',
                'Mengurangi lemak jenuh',
                'Aktivitas fisik ≥30 menit/hari',
                'Menjalankan program penurunan berat badan',
                'Melakukan relaksasi/meditasi/dzikir',
                'Menghindari stres berlebihan',
                'Mengukur tekanan darah sesuai jadwal',
                'Mencatat hasil tekanan darah',
                'Konsultasi tenaga kesehatan sesuai jadwal',
            ],
        ],
        'Tinggi' => [
            'items' => [
                'Minum obat antihipertensi sesuai jadwal',
                'Tidak melewatkan dosis obat',
                'Tidak menghentikan obat tanpa konsultasi',
                'Kontrol dokter sesuai jadwal',
                'Membatasi garam <5 gram/hari',
                'Menghindari makanan tinggi natrium',
                'Mengonsumsi makanan tinggi serat',
                'Mengonsumsi buah dan sayur setiap hari',
                'Olahraga sesuai kondisi kesehatan',
                'Menghindari gaya hidup sedentari',
                'Melakukan relaksasi/meditasi/dzikir',
                'Mengendalikan stres harian',
                'Mengukur tekanan darah harian',
                'Mencatat hasil tekanan darah',
                'Memantau gejala hipertensi',
                'Keluarga membantu pengawasan obat',
                'Keluarga mendukung pola hidup sehat',
                'Keluarga memahami tanda bahaya hipertensi',
            ],
        ],
    ],

    'rheumatoid_arthritis' => [
        'Rendah' => [
            'items' => [
                'Melakukan peregangan sendi setiap hari',
                'Melakukan aktivitas fisik ringan (jalan kaki, bersepeda, senam)',
                'Tidak duduk atau berbaring terlalu lama',
                'Menjaga berat badan ideal',
                'Mengonsumsi buah dan sayuran',
                'Mengonsumsi makanan sumber omega-3',
                'Mengurangi makanan tinggi gula',
                'Mengurangi makanan tinggi lemak jenuh',
                'Tidak merokok',
                'Menghindari paparan asap rokok',
                'Melakukan manajemen stres',
                'Memantau nyeri atau pembengkakan sendi',
                'Mencatat kekakuan sendi yang berulang',
            ],
        ],
        'Sedang' => [
            'items' => [
                'Melakukan latihan rentang gerak sendi 15–30 menit',
                'Menggerakkan sendi secara perlahan dan teratur',
                'Menggunakan kompres hangat saat sendi kaku',
                'Mengistirahatkan sendi saat nyeri meningkat',
                'Menghindari aktivitas berat',
                'Mengonsumsi ikan laut sumber omega-3',
                'Mengonsumsi sayuran hijau',
                'Mengonsumsi buah-buahan',
                'Mengurangi makanan cepat saji',
                'Mengurangi makanan tinggi gula',
                'Melakukan relaksasi/meditasi/dzikir',
                'Tidur 7–8 jam',
                'Mencatat tingkat nyeri sendi harian',
                'Mencatat lama kekakuan pagi hari',
                'Memantau pembengkakan sendi',
                'Memantau kemerahan sendi',
                'Konsultasi ke fasilitas kesehatan bila diperlukan',
            ],
        ],
        'Tinggi' => [
            'items' => [
                'Minum obat sesuai resep',
                'Tidak menghentikan obat tanpa konsultasi',
                'Mematuhi jadwal kontrol',
                'Menghindari mengangkat beban berat',
                'Menggunakan alat bantu bila diperlukan',
                'Menyeimbangkan aktivitas dan istirahat',
                'Melakukan latihan rentang gerak sendi',
                'Melakukan latihan penguatan otot',
                'Menghindari olahraga benturan tinggi saat nyeri',
                'Mengonsumsi omega-3',
                'Mengonsumsi sayuran dan buah',
                'Mengonsumsi makanan tinggi serat',
                'Membatasi gula',
                'Membatasi garam',
                'Membatasi lemak jenuh',
                'Mencatat jumlah sendi nyeri/bengkak',
                'Mencatat tingkat nyeri harian',
                'Mencatat lama kekakuan pagi hari',
                'Mencatat kemampuan aktivitas sehari-hari',
                'Keluarga membantu mengingatkan obat',
                'Keluarga membantu aktivitas saat nyeri',
                'Keluarga memberikan dukungan emosional',
            ],
        ],
    ],
];
